[package]
name = "less-sync-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
less-sync-core = { path = "../core" }
thiserror.workspace = true
