[package]
name = "less-sync-server"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
less-sync-app = { path = "../../crates/app" }
tokio.workspace = true
tracing-subscriber.workspace = true
